[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "GridFinder"
version = "0.1.0"
description = "Tool for testing table-based Reinforcement Learning algorithms and Comparing them to traditional smart search methods"
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }
authors = [
  { name = "Joshua Stenger", email = "JoshuaStenger12@outlook.com" },
  { name = "Prasenjit Karmakar", email = "prasenjitkarmakar52282@gmail.com" },
]
dependencies = [
  "numpy==2.4.4",
  "pygame==2.6.1",
  "torch==2.11.0",
]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
]

[project.urls]
Homepage = "https://github.com/StengerJ/GridFinder"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["gridworld*"]

[tool.setuptools.package-data]
"gridworld.modules" = ["images/*.png"]
